### ISSUE TITLE
Sample spec.js file is broken in generator-flight-pacakge@0.5.0 

### ISSUE THREAD

**Issue by floatdrop** [flightjs/generator-flight-package#15]
Fresh init of generator-flight-package@0.5.0 and running `npm test` gives:

``` bash
Firefox 32.0.0 (Mac OS X 10.9) ERROR
  ReferenceError: describeComponent is not defined
  at /Users/floatdrop/flight-bootstrap/test/spec/bootstrap.spec.js:3
Firefox 32.0.0 (Mac OS X 10.9): Executed 0 of 0 ERROR (0 secs / 0 secs)
```

I'm fairly new to karma test tool and have no idea, from where `describeComponent` should be imported (global scope?).

**Comment by necolas** [comment]
Is jasmine-flight installed?

**Comment by floatdrop** [comment]
@necolas yep. but into `vendor` directory. Fixed paths and test became green.
