### ISSUE TITLE
Return function after defining

### ISSUE THREAD

**Issue by danse** [flightjs/generator-flight-package#3]
After generating a package i see that the `return` statement in the component is _before_ the component function definition. This is also the style used in general in flight documentation.

I would ask to invert the order, though, because using a function before declaring it raises an error on some linters.

**Comment by necolas** [comment]
Thanks but the generated package comes with a JSHint config that allows this. You should be using that.

Function hoisting is a feature of the language and in this case helps to expose early in the file that you're exporting a specific function as a flight component.
