### ISSUE TITLE
Karma tests break with jasmine-jquery 2.0

### ISSUE THREAD

**Issue by paulwib** [flightjs/generator-flight-package#8]
Hey, the dependency on jasmine-jquery as "*" means the recent 2.0 release will get installed, but seems to be broken (try creating a new package and do `karma start`).

Not sure what the incompatibility is, but maybe a version for jasmine-jquery could be specified to avoid it? 1.7.0 works great :)

**Comment by necolas** [comment]
Should be fixed now
